version: '3.8'

services:
  frontend:
    container_name: game-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    # command: npm run start -- --host 0.0.0.0
    ports:
      - '4200:4200' # Mapeia a porta 4200 no host para a porta 80 no container
    volumes:
      - .:/app
      # - /app/node_modules # Evita sobrescrever node_modules do container
    environment:
      NODE_ENV: development
      API_URL: 'http://host.docker.internal:3000'
      LOG_LEVEL: debug
    # network_mode: host
